# Use the official Node.js image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN pnpm install

# Copy the rest of the application files
COPY . .

# Expose the application port
EXPOSE 5173

# Command to start the server
CMD ["pnpm", "dev"]

